### PR TITLE
Upgrade all internal dependencies to their latest version

### PR DESCRIPTION
**Pull request by vincentfree**

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Comment by vincentfree** [comment]
I have updated the swagger name to openapiv2 since It has been changed in the newer version of **grpc-gateway**. Info can be found here: https://github.com/grpc-ecosystem/grpc-gateway

Though this changed the repo that uses this image also needs to update the name from swagger to openapiv2 as described on the **grpc-gateway** page.

**Comment by vincentfree** [comment]
I have updated the swagger name to openapiv2 since It has been changed in the newer version of grpc-gateway. Info can be found here: https://github.com/grpc-ecosystem/grpc-gateway

Though this changed the repo that uses this image also needs to update the name from swagger to openapiv2 as described on the *grpc-gateway page.

**Comment by bogdandrutu** [comment]
Please resolve conflicts and fix the build.

**Comment by vincentfree** [comment]
> Please resolve conflicts and fix the build.

I have fixed the issues. There were some third party proto files being copied in the v1.x version of grpc gateway that were removed for version v2.x
Removed the copy statements, now the build passes.

**Comment by vincentfree** [comment]
@bogdandrutu I think the PR is ready for your review

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
