### PR TITLE
Add schema file tool

### PR DESCRIPTION
**Pull request by tigrannajaryan**
This can be used in specification repo to validate the schema files.

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-approvers please review.

**Review by SergeyKanzhelev — APPROVED** [review]
lgtm for implemented checks. Curious do you have any other checks in mind?

Also, adding unit tests would be a nice addition demonstrating what the tool does

**Comment by tigrannajaryan** [comment]
> lgtm for implemented checks. Curious do you have any other checks in mind?

Yes, it is possible to add more checks (e.g. that the historical versions agree with each other). This is just the first step, we can build on top of it.

> 
> Also, adding unit tests would be a nice addition demonstrating what the tool does

Good point. 

This primarily uses the schema parser from Go SDK which already has some unit tests: https://github.com/open-telemetry/opentelemetry-go/blob/main/schema/v1.0/parser_test.go

Let me see if I can add any useful tests here as well.

**Comment by tigrannajaryan** [comment]
Added a few tests.

**Comment by tigrannajaryan** [comment]
Merging to start using in the spec. More improvements can be in future PRs.

**Pull request merged**
